baseurl = "http://wobbly.earth"
languageCode = "en-us"
title = "Wobbly Earth"
theme = "HugoMDL"
MetaDataFormat = "yaml"
[permalinks]
	page = "/:title/"
	about = "/:filename/"
[params]
    author = "Roelof Rietbroek"
    avatar = "/images/avatar.jpg"
#    background = "/images/background.jpg" (not working )
    description = "A place to publish my incomprehensible ramblings" #meta description
    image = "/images/avatar.jpg" #for frontpage profile card
    website = "example.com"
    email = "roelof@geod.uni-bonn.de"
    twitter = "https://twitter.com/r_rietje"
    github = "https://github.com/strawpants/"
#    linkedin = "https://linkedin.com/in/firstname_lastname/"
#    facebook = "https://facebook.com/firstname_lastname/"
    copyrightyear = "2016"
    frontpageposts = 3 #number of post cards to display on frontpage
    
